<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupTransactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupTransactionsRepository extends EntityRepository
{
    public function searchAction()
    {
        return $this->createQueryBuilder('g')
//            ->leftJoin('g.transactionId', 'transaction_id')
            ->groupBy('g.createDate')
            ->getQuery()
            ->getResult();
    }
}
