<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserWalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWalletRepository extends EntityRepository
{
    public function searchMoney($usrid)
    {
        $firstmonth = new \DateTime('first day of this month');
        $endDate = new \DateTime('last day of this month');

        return $this->createQueryBuilder('w')
            ->select('Sum(w.quantity)')
            ->where('w.userId = :userid')
            ->andWhere('w.createDate BETWEEN :start AND :end')
            ->setParameter('userid',$usrid)
            ->setParameter('start', $firstmonth)
            ->setParameter('end', $endDate)
            ->getQuery()
            ->getResult();
    }

    public function searchLastMoney($usrid)
    {
        $firstmonth = new \DateTime('first day of last month');
        $endDate = new \DateTime('last day of last month');

        return $this->createQueryBuilder('w')
            ->select('Sum(w.quantity)')
            ->where('w.userId = :userid')
            ->andWhere('w.createDate BETWEEN :start AND :end')
            ->setParameter('userid', $usrid)
            ->setParameter('start', $firstmonth)
            ->setParameter('end', $endDate)
            ->getQuery()
            ->getResult();
    }

}
