<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserWalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWalletRepository extends EntityRepository
{
    public function budgetForMonth($usrid, $month = null)
    {
        return $this->createQueryBuilder('w')
            ->select('Sum(w.quantity)')
            ->where('w.userId = :userid')
            ->andWhere('MONTH(w.createDate) = :month')
            ->setParameter('userid',$usrid)
            ->setParameter('month', $month)
            ->getQuery()
            ->getResult();
    }
}
