<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserWalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWalletRepository extends EntityRepository
{
    public function searchMoney()
    {
        return $this->createQueryBuilder('w')
            ->select('Sum(w.quantity)')
            ->getQuery()
            ->getResult();
    }
}
