# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        my_db_provider:
            entity: { class: AppBundle:User, property: email }
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_USER: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_USER]
        ROLE_INACTIVE: ROLE_INACTIVE
    firewalls:
#        access_denied_url: login
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            context: main
            provider: my_db_provider
            anonymous: ~
            logout: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
            logout:
                path:   /logout
                target: /login



    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/month/*, roles: ROLE_USER }
        - { path: ^/edit/*, roles: ROLE_USER }
